// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	slack "github.com/jackchuka/slackcli/internal/slack"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddReaction mocks base method.
func (m *MockService) AddReaction(channelID, timestamp, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReaction", channelID, timestamp, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReaction indicates an expected call of AddReaction.
func (mr *MockServiceMockRecorder) AddReaction(channelID, timestamp, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReaction", reflect.TypeOf((*MockService)(nil).AddReaction), channelID, timestamp, name)
}

// ArchiveChannel mocks base method.
func (m *MockService) ArchiveChannel(channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveChannel", channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveChannel indicates an expected call of ArchiveChannel.
func (mr *MockServiceMockRecorder) ArchiveChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveChannel", reflect.TypeOf((*MockService)(nil).ArchiveChannel), channelID)
}

// AuthTest mocks base method.
func (m *MockService) AuthTest() (*slack.AuthTestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthTest")
	ret0, _ := ret[0].(*slack.AuthTestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthTest indicates an expected call of AuthTest.
func (mr *MockServiceMockRecorder) AuthTest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthTest", reflect.TypeOf((*MockService)(nil).AuthTest))
}

// CreateChannel mocks base method.
func (m *MockService) CreateChannel(name string, isPrivate bool) (*slack.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", name, isPrivate)
	ret0, _ := ret[0].(*slack.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockServiceMockRecorder) CreateChannel(name, isPrivate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockService)(nil).CreateChannel), name, isPrivate)
}

// DeleteFile mocks base method.
func (m *MockService) DeleteFile(fileID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockServiceMockRecorder) DeleteFile(fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockService)(nil).DeleteFile), fileID)
}

// DeleteMessage mocks base method.
func (m *MockService) DeleteMessage(channelID, timestamp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", channelID, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockServiceMockRecorder) DeleteMessage(channelID, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockService)(nil).DeleteMessage), channelID, timestamp)
}

// DownloadFile mocks base method.
func (m *MockService) DownloadFile(url, destPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", url, destPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockServiceMockRecorder) DownloadFile(url, destPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockService)(nil).DownloadFile), url, destPath)
}

// EditMessage mocks base method.
func (m *MockService) EditMessage(channelID, timestamp, text string) (*slack.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessage", channelID, timestamp, text)
	ret0, _ := ret[0].(*slack.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockServiceMockRecorder) EditMessage(channelID, timestamp, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockService)(nil).EditMessage), channelID, timestamp, text)
}

// GetChannelInfo mocks base method.
func (m *MockService) GetChannelInfo(channelID string) (*slack.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelInfo", channelID)
	ret0, _ := ret[0].(*slack.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelInfo indicates an expected call of GetChannelInfo.
func (mr *MockServiceMockRecorder) GetChannelInfo(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelInfo", reflect.TypeOf((*MockService)(nil).GetChannelInfo), channelID)
}

// GetFileInfo mocks base method.
func (m *MockService) GetFileInfo(fileID string) (*slack.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileInfo", fileID)
	ret0, _ := ret[0].(*slack.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileInfo indicates an expected call of GetFileInfo.
func (mr *MockServiceMockRecorder) GetFileInfo(fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileInfo", reflect.TypeOf((*MockService)(nil).GetFileInfo), fileID)
}

// GetUserInfo mocks base method.
func (m *MockService) GetUserInfo(userID string) (*slack.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", userID)
	ret0, _ := ret[0].(*slack.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockServiceMockRecorder) GetUserInfo(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockService)(nil).GetUserInfo), userID)
}

// GetUserPresence mocks base method.
func (m *MockService) GetUserPresence(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPresence", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPresence indicates an expected call of GetUserPresence.
func (mr *MockServiceMockRecorder) GetUserPresence(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPresence", reflect.TypeOf((*MockService)(nil).GetUserPresence), userID)
}

// InviteToChannel mocks base method.
func (m *MockService) InviteToChannel(channelID string, userIDs ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{channelID}
	for _, a := range userIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InviteToChannel", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteToChannel indicates an expected call of InviteToChannel.
func (mr *MockServiceMockRecorder) InviteToChannel(channelID any, userIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{channelID}, userIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteToChannel", reflect.TypeOf((*MockService)(nil).InviteToChannel), varargs...)
}

// KickFromChannel mocks base method.
func (m *MockService) KickFromChannel(channelID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KickFromChannel", channelID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// KickFromChannel indicates an expected call of KickFromChannel.
func (mr *MockServiceMockRecorder) KickFromChannel(channelID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KickFromChannel", reflect.TypeOf((*MockService)(nil).KickFromChannel), channelID, userID)
}

// ListChannels mocks base method.
func (m *MockService) ListChannels(params slack.PaginationParams) (*slack.PaginatedResult[slack.Channel], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", params)
	ret0, _ := ret[0].(*slack.PaginatedResult[slack.Channel])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockServiceMockRecorder) ListChannels(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockService)(nil).ListChannels), params)
}

// ListFiles mocks base method.
func (m *MockService) ListFiles(params slack.PaginationParams, channelID, userID string) (*slack.PaginatedResult[slack.File], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", params, channelID, userID)
	ret0, _ := ret[0].(*slack.PaginatedResult[slack.File])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockServiceMockRecorder) ListFiles(params, channelID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockService)(nil).ListFiles), params, channelID, userID)
}

// ListMessages mocks base method.
func (m *MockService) ListMessages(params slack.ListMessagesParams) (*slack.PaginatedResult[slack.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", params)
	ret0, _ := ret[0].(*slack.PaginatedResult[slack.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockServiceMockRecorder) ListMessages(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockService)(nil).ListMessages), params)
}

// ListReactions mocks base method.
func (m *MockService) ListReactions(userID string, params slack.PaginationParams) (*slack.PaginatedResult[slack.ReactedItem], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReactions", userID, params)
	ret0, _ := ret[0].(*slack.PaginatedResult[slack.ReactedItem])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReactions indicates an expected call of ListReactions.
func (mr *MockServiceMockRecorder) ListReactions(userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReactions", reflect.TypeOf((*MockService)(nil).ListReactions), userID, params)
}

// ListUsers mocks base method.
func (m *MockService) ListUsers(params slack.PaginationParams) (*slack.PaginatedResult[slack.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", params)
	ret0, _ := ret[0].(*slack.PaginatedResult[slack.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockServiceMockRecorder) ListUsers(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockService)(nil).ListUsers), params)
}

// RemoveReaction mocks base method.
func (m *MockService) RemoveReaction(channelID, timestamp, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReaction", channelID, timestamp, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReaction indicates an expected call of RemoveReaction.
func (mr *MockServiceMockRecorder) RemoveReaction(channelID, timestamp, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReaction", reflect.TypeOf((*MockService)(nil).RemoveReaction), channelID, timestamp, name)
}

// SearchMessages mocks base method.
func (m *MockService) SearchMessages(params slack.SearchParams) (*slack.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMessages", params)
	ret0, _ := ret[0].(*slack.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMessages indicates an expected call of SearchMessages.
func (mr *MockServiceMockRecorder) SearchMessages(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMessages", reflect.TypeOf((*MockService)(nil).SearchMessages), params)
}

// SendMessage mocks base method.
func (m *MockService) SendMessage(params slack.SendMessageParams) (*slack.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", params)
	ret0, _ := ret[0].(*slack.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockServiceMockRecorder) SendMessage(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockService)(nil).SendMessage), params)
}

// SetChannelPurpose mocks base method.
func (m *MockService) SetChannelPurpose(channelID, purpose string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChannelPurpose", channelID, purpose)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetChannelPurpose indicates an expected call of SetChannelPurpose.
func (mr *MockServiceMockRecorder) SetChannelPurpose(channelID, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChannelPurpose", reflect.TypeOf((*MockService)(nil).SetChannelPurpose), channelID, purpose)
}

// SetChannelTopic mocks base method.
func (m *MockService) SetChannelTopic(channelID, topic string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChannelTopic", channelID, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetChannelTopic indicates an expected call of SetChannelTopic.
func (mr *MockServiceMockRecorder) SetChannelTopic(channelID, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChannelTopic", reflect.TypeOf((*MockService)(nil).SetChannelTopic), channelID, topic)
}

// UploadFile mocks base method.
func (m *MockService) UploadFile(channelID, filename, title string, reader io.Reader) (*slack.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", channelID, filename, title, reader)
	ret0, _ := ret[0].(*slack.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockServiceMockRecorder) UploadFile(channelID, filename, title, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockService)(nil).UploadFile), channelID, filename, title, reader)
}
